---------------------------------------Courses-----------------------------------------------
-- Sequence
CREATE SEQUENCE ADMIN.COURSES_SEQ
START WITH 10
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;
-- Trigger
CREATE TRIGGER ADMIN.COURSES_TRG
BEFORE INSERT
ON ADMIN.COURSES
REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
BEGIN
  :new.COURSE_ID := COURSES_SEQ.nextval;
END COURSES_TRG;
 
------------------------------------------Student---------------------------------------------
-- Sequence
CREATE SEQUENCE ADMIN.STUDENTS_SEQ
START WITH 3
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;
-- Trigger
CREATE TRIGGER ADMIN.STUDENTS_TRG
BEFORE INSERT
ON ADMIN.STUDENTS
REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
BEGIN
  :new.STUDENT_ID := STUDENTS_SEQ.nextval;
END STUDENTS_TRG;
